"""empty message

Revision ID: 3529d5be9db0
Revises: None
Create Date: 2015-04-09 19:46:54.193704

"""

# revision identifiers, used by Alembic.
revision = '3529d5be9db0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    ### end Alembic commands ###
